spring :
  application:
    name: ionela-internship #NUMELE PROIECTULUI

  #CONFIGURARI PENTRU DATABASE
  datasource:
    url: jdbc:mariadb://localhost:3306/Studenti
    username: root
    password: 123456789!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
server:
  port: 8081



